//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\School\Compilacion\Cool_Compiler\Cool_Compiler\Grammar\Cool\Cool.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CoolParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ICoolVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>prog</c>
	/// labeled alternative in <see cref="CoolParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] CoolParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classlist</c>
	/// labeled alternative in <see cref="CoolParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClasslist([NotNull] CoolParser.ClasslistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.classdefine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassdefine([NotNull] CoolParser.ClassdefineContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>featuremet</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeaturemet([NotNull] CoolParser.FeaturemetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>featureprop</c>
	/// labeled alternative in <see cref="CoolParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeatureprop([NotNull] CoolParser.FeaturepropContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] CoolParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] CoolParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.formal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal([NotNull] CoolParser.FormalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>log_arit</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLog_arit([NotNull] CoolParser.Log_aritContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>let</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet([NotNull] CoolParser.LetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseof</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseof([NotNull] CoolParser.CaseofContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] CoolParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>isvoid</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsvoid([NotNull] CoolParser.IsvoidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newtype</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewtype([NotNull] CoolParser.NewtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>getid</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetid([NotNull] CoolParser.GetidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>log_neg</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLog_neg([NotNull] CoolParser.Log_negContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacion</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacion([NotNull] CoolParser.AsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracket</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket([NotNull] CoolParser.BracketContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] CoolParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumsub</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumsub([NotNull] CoolParser.SumsubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multdiv</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultdiv([NotNull] CoolParser.MultdivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>corpus</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCorpus([NotNull] CoolParser.CorpusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] CoolParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifelse</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfelse([NotNull] CoolParser.IfelseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] CoolParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dispatch</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatch([NotNull] CoolParser.DispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bool</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] CoolParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>explicitdispatch</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitdispatch([NotNull] CoolParser.ExplicitdispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compar</c>
	/// labeled alternative in <see cref="CoolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompar([NotNull] CoolParser.ComparContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.argexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgexpr([NotNull] CoolParser.ArgexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.stamentlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStamentlist([NotNull] CoolParser.StamentlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.stament"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStament([NotNull] CoolParser.StamentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CoolParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch([NotNull] CoolParser.BranchContext context);
}
